services:
  kafka:
    image: confluentinc/cp-kafka:7.8.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "my-cluster-id"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:19092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - financial-pipeline

  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.6
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:19092"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - financial-pipeline

  spark-master:
    image: blnkoff/spark-master:latest
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"  # Spark UI
    networks:
      - financial-pipeline

  spark-worker:
    image: blnkoff/spark-worker:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - financial-pipeline

  spark-driver:
    build:
      context: ./spark-driver
      dockerfile: Dockerfile
    container_name: spark-driver
    depends_on:
      - spark-master
      - kafka
      - schema-registry
    volumes:
      - ./src:/app/src        # source code
      - ./requirements:/app/requirements  # requirements files
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - KAFKA_BOOTSTRAP_SERVERS=kafka:19092
    networks:
      - financial-pipeline

networks:
  financial-pipeline:
    driver: bridge

volumes:
  kafka-data:
